### ISSUE TITLE
Robots not generating any <meta name="robots"> tag?

### ISSUE THREAD

**Issue by benface** [ethercreative/seo#123]
I am sorry if this is not a proper bug report, but I don't understand how the "Robots" section of the SEO field works. I enabled "noindex" for an entry, but there is no `<meta name="robots" content="noindex">` generated in the HTML, and it also doesn't seem to have any impact on the `robots.txt` file. So what does it do?

Thank you.

**Comment by Tam** [comment]
SEO sets the `X-Robots-Tag` header instead of outputting a robots meta tag.

**Comment by thijskaspers** [comment]
Thanks for the answer Tam, we had the same question.

Why did ethercreative chose to use the X-Robots-Tag instead of rendering a meta robots tag in the head? We were also thinking that the meta robots tag wasn't working properly as it rendered nothing in the head. We would like to be able to set the robots tag on static pages and were looking for a way with the `{% set seo = craft.seo.custom(.........) %}` snippet, but found no options, now we know why. Not an issue of course, we can add the tag manually, but it wasn't clear in the docs.

The X-Robots-Tag is a 'minor' problem for us. On staging and acceptance environments our servers are set-up so that nginx automatically adds "noindex, nofollow" to all pages via the X-Robots-Tag so developers won't have to worry about it. Our Craft websites using your SEO plugin now have two X-Robots-Tags in the header, which might conflict.
