### ISSUE TITLE
Redirect performance?

### ISSUE THREAD

**Issue by proimage** [ethercreative/seo#129]
As mentioned in [this SO answer](https://stackoverflow.com/a/4435531/999556), long .htaccess files can slow things down since they need to be processed for every http request at that level and below.

I have a client with an .htaccess that has about 3000 `RewriteRule` lines. Would there be any performance benefit or detriment to moving these items into your SEO plugin?

**Comment by Tam** [comment]
SEO will only look for a redirect if a page 404s. This means any overhead involved in checking for a redirect will only occur on those pages, rather than every page load.

I just ran a test on my local dev environment (equivalent to a $5 DigitalOcean server or lower) with +3000 redirects and the average TTFB was ~400ms, so I don't think you'll have any issues with any overhead but I'd be interested in any benchmarks you gather.

**Comment by proimage** [comment]
Great, thanks for the info, that's very useful... and a much more attractive implementation to shove 3k redirects into. ;)
