### ISSUE TITLE
Not reading keyword in slug for multi-word keywords

### ISSUE THREAD

**Issue by alexjcollins** [ethercreative/seo#152]
### Description

If your keyword has more than one word, even if the words are present in the slug it will fail the test and return `The URL does not contain the keyword. Try adding it to the slug.`

### Steps to reproduce

1. Create an entry with a multi-word slug
2. Add those words as a keyword in the SEO field
3. View the red dot 🔴

### Additional info

- Craft version: 3.0.31
- SEO version: 3.4.4

**Comment by niektenhoopen** [comment]
Any updates on this issue?

I have the same issue (I guess... because this issue can be interpreted in different ways)

For example: I entered the keyword "beautiful flower" (without quotes) and the slug of the page is "beautiful-flower" (without the quotes). It seems like the plugin does not realize that the slug contains "beautiful flower" but only with a dash instead of a space.

If I enter both keywords "beautiful" and "flower", there is no problem, but I entered it as one keyword with a space between both words.

I am on Craft 3.1.33 and SEO 3.5.4
