### ISSUE TITLE
Social titles and descriptions uneditable

### ISSUE THREAD

**Issue by billythekid** [ethercreative/seo#185]
It seems that an update has made FB & Twitter titles and descriptions uneditable. They appear to only take the SEO tab's values.

Also, old saved (pre 3.5.0 possibly) values in these fields are no longer overwritten by edits to the SEO tab values. New entries don't seem to have this issue and the social descriptions are changed when the SEO tab's values are changed and the entry is saved.

The image fields for social stuff are updating fine.

**Comment by benface** [comment]
Seeing the same thing here.

**Comment by clarknelson** [comment]
same issue here

**Comment by jamesirving** [comment]
same issue here

**Comment by alexjcollins** [comment]
Hi all, we removed the social title and description editing [in a recent update](https://github.com/ethercreative/seo/blob/v3/CHANGELOG.md#changed-1).

We really wanted to get the new META editing functionality out as the way it had been was causing a ton of issues for people. Adding the same functionality in for social would have delayed that feature unduly. 

We plan to add the functionality back in soon and it will mirror the behaviour of the new token system for added flexibility. I'll keep you all updated with progress and leave this issue open so others are aware.

Sorry if that has majorly inconvenienced any of you! Feel free to reach out if you have any questions.

**Comment by billythekid** [comment]
Thanks for this update Alex and apologies for not properly reading the changelog. 

Look forward to seeing the re-implementation. Keep up the good work!

**Comment by jongbelegen** [comment]
When do you expect do get this feature out?

We upgraded without checking the changelogs and our client need to be able to change social meta data. Is there a easy way of downgrading?

**Comment by kaspar-allenbach** [comment]
When do you plan on bringing this feature back? A SEO plugin where you can't edit the SEO is a bit weird.

**Comment by alexjcollins** [comment]
We'll discuss today and let you know.

Out of interest, could you all describe generally how you approach this with your clients? How does a typical SEO title look vs typical social titles? Are Facebook and Twitter titles different?

**Comment by kaspar-allenbach** [comment]
I'd say they are almost always the same. Before I used your plugin I did the seo by hand.
I've set up a **Title** & **Description** & **Title Suffix Field** and used them for everything: Google, Facebook and Twitter. Unlike the images where different aspect ratios may apply.

The strength of your former editable social fields was the imediate visibility on how it will look. I have a hard time convincing my clients to fill out SEO because they believe if it's not visible on the page, it doesn't matter. Your plugin makes a very clear visual representation of what is necessary for social media. I find it a much better approach than seting up some abstract seo rules even if it means adding the content manually for each social media profile.

**Comment by clarknelson** [comment]
I like being able to edit how social will display directly, but I appreciate the plugin overall and am looking forward to any updates or improvements.

**Comment by coryzibell** [comment]
Hey @alexjcollins do you have an update on when you plan on re-introducing this feature? A few of our clients rely on it. They mostly change the Facebook meta data for organic social campaigns, and like to tweak the meta to match. Thanks!

**Comment by aaronwaldon** [comment]
I too had a client that reported this functionality as broken. The social preview fields' are not edible. I thought something was wrong before I found this support thread.

It seems that simply removing the `readonly` attribute from the input and textarea inside the social preview content in the fieldtype.twig template fixes this issue. Could those attributes be removed in order to allow clients to keep using the fields until the new token syntax is ready?

**Comment by harryfk** [comment]
+1

A fix for this would be greatly appreciated. Until then I’ll keep deleting the readonly attributes. 😕

**Comment by MichaelWheldon** [comment]
Not sure how risky this is, but a client just ran into this issue. How I got around this was to inspect the element and remove the readOnly property, make my change and then save.

Seems to have gone through to our meta tags on the frontend. But yeah... not ideal and would be great to get this feature back soon :)

**Comment by alexjcollins** [comment]
@MichaelWheldon we have fixed this; are you definitely running the latest version of SEO?
