### ISSUE TITLE
Typo in "Opitmisation checklist"

### ISSUE THREAD

**Issue by jlcharette** [ethercreative/seo#227]
### Description

Typo in "**Opit**misation checklist" see screenshot:

https://imgur.com/oOxFgjD

### Additional info

- Craft version: Craft Solo 3.2.7
- SEO version: 3.6.1.1
- PHP version: 7.2.19
- Database driver & version: MySQL 5.7.27
- Other Plugins: LinkIt, Mix, Redactor, Relabel, Neo, Super Tables, Table Maker

**Comment by alexjcollins** [comment]
@jlcharette thanks for the note. It's technically correct as it's written in British English (where we're at!). We're currently considering localising (oop, there's another one!) the plugin, though.

**Comment by jlcharette** [comment]
**Opit**misation => **Opti**mization/**Opti**misation? I have never seen "**Opit**misation" before tbh.

**Comment by jlcharette** [comment]
@alexjcollins the funny part is that the string below is correct "Use this handy chart to **opti**mise"... But the title reads "**Opit**misation". The "ti" are inverted.

**Comment by jlcharette** [comment]
https://imgur.com/YujQKZP

**Comment by alexjcollins** [comment]
@jlcharette Sorry - my mistake! Before you added the **bold** I read over the actual typo and assumed the issue you had was with the use of an `s` instead of a `z`. I have added a fix which will be included in the next release.

https://github.com/ethercreative/seo/commit/32f838efbae656857dfc1652956774b256c86a8b

**Comment by jlcharette** [comment]
Excellent! Thanks for the amazing plugin btw.
