### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by MrGlasspoole** [ethercreative/seo#230]
I must be blind. I don't see examples or what needs to be done.
I thought after the installation i have a SEO tab in my entries?

**Comment by alexjcollins** [comment]
@MrGlasspoole There are two main things you need to do to get up and running with page meta:

**Create and configure an SEO Field and add it to all your sections/entry types.**
To do this, you'll need to go to `Settings` → `Fields` → `+ New Field`. Give the field a name like 'SEO' and select the field type as SEO. That will show a bunch of options which you can then follow to configure the filed type.
Finally, you then need to go into each section to attach that field. That's where you can add a separate tab for the field.

**Add the SEO meta hook to your template.**
Now that you've added the ability to create and edit meta in the admin, you need that to pull through to your templates. To do this, you'll need to add the `{% hook "seo" %}` tag to your main layout file (or wherever else your page head is being output). When doing this remember to also remove any meta tags you had before, otherwise, you'll have double in the markup.

I hope this helps!
