### ISSUE TITLE
PHP error sitemap

### ISSUE THREAD

**Issue by tim-van-dijkhuizen** [ethercreative/seo#296]
### Description
When visiting my sitemap url I get the following PHP error:
https://pastebin.com/sjQp0LT9

### Steps to reproduce

1. Visit sitemap  url
2. Boom, error!

### Additional info

- Craft version: 3.4.14
- SEO version: 3.6.3
- PHP version: 7.2.18
- Database driver & version: MySQL 5.5.5

**Comment by alexjcollins** [comment]
Have you enabled sections in the sitemap?

**Comment by tim-van-dijkhuizen** [comment]
I did and my other sitemaps were working. I am no longer able to reproduce this as I'm now using a different setup.

**Comment by nstcactus** [comment]
I got this error too and after digging a little, it appears to affect sections having several entry types with different SEO field handles. In my case I had a **Products** section, with 2 entry types:

| Entry type handle | SEO field handle |
| ------------------ | ---------------- |
| products | productsSeo |
| productCategories | productCategoriesSeo |

The exception is thrown here, because `$seoField` is null.
https://github.com/ethercreative/seo/blob/58de8d61979ce2e3030303f72fff92229118388f/src/services/SitemapService.php#L306-L307

This is because `$seoFieldHandle` is set to the handle of the last SEO field of the first entry in the section, regardless of its entry type.

https://github.com/ethercreative/seo/blob/58de8d61979ce2e3030303f72fff92229118388f/src/services/SitemapService.php#L286-L297

To solve this something mapping each entry type to an seo field handle must be used to retrieve the SEO field.
