### ISSUE TITLE
Sitemap.xml not rendering correctly

### ISSUE THREAD

**Issue by sgalligan** [ethercreative/seo#386]
### Description
Our install of SEO is rendering the sitemap.xml file incorrectly. Rather than outputting entries for each individual page, it is outputting a general, autogenerated URL for each section enabled for the sitemap. The resulting sitemap looks like the following:

```
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
<sitemap>
<loc>https://mysiteurl.com/sitemap_sections_4_0.xml</loc>
<lastmod>2022-01-01T09:10:30-08:00</lastmod>
</sitemap>
<sitemap>
<loc>https://mysiteurl.com/sitemap_sections_3_0.xml</loc>
<lastmod>2022-01-01T09:10:30-08:00</lastmod>
</sitemap>
<sitemap>
<loc>https://mysiteurl.com/sitemap_sections_6_0.xml</loc>
<lastmod>2022-01-01T09:10:30-08:00</lastmod>
</sitemap>
<sitemap>
<loc>https://mysiteurl.com/sitemap_sections_1_0.xml</loc>
<lastmod>2022-01-01T09:10:30-08:00</lastmod>
</sitemap>
<sitemap>
<loc>https://mysiteurl.com/sitemap_sections_5_0.xml</loc>
<lastmod>2022-01-01T09:10:30-08:00</lastmod>
</sitemap>
</sitemapindex>
```
For what it's worth, in the Sitemap tab, the plugin is not showing the URL Format column as shown [here](https://github.com/ethercreative/seo#the-sitemap), although I believe that must be the intended function since there is no corresponding code to generate the column in the SitemapService.php file?

### Additional info

- Craft version: 3.7.26
- SEO version: 3.7.4
- PHP version: 7.4.27
- Database driver & version: MySQL 5.7.36
- Other Plugins: Contact Form, Contact Form Honeypot, Control Panel CSS, Position Fieldtype, Redactor, Shield, Super Table, Typogrify

**Comment by alexjcollins** [comment]
Hi @sgalligan 

The formatting of the sitemap is intentional - we're utilising sitemap groups in order to prevent loading potentially huge sitemaps on sites with a lot of entries.

[You can read more here](https://developers.google.com/search/docs/advanced/sitemaps/large-sitemaps?hl=en&visit_id=637768231616273445-2813626606&rd=1).

As for the URL Format, that's correct - we pulled that functionality.

Cheers!

---

Similar to: https://github.com/ethercreative/seo/issues/299

**Comment by sgalligan** [comment]
:: facepalm :: 

Thank you.
