### ISSUE TITLE
Packagist  not up to date

### ISSUE THREAD

**Issue by fleaz** [ethercreative/seo#405]
### Description
Hey,

currently the latest two releases are missing on Packagist. The latest version on there is 4.0.0 but 4.0.1 and 4.0.2 are missing.

Could you please take a look whats broken? Because especially 4.0.2 is required for one of our customers to update to Craft 4

Best,
Felix

**Comment by rostockahoi** [comment]
In the meantime you can directly require the commit tagged with `v4.0.2` with
`composer require ether/seo:dev-v4-dev#9f563663e103bca1da02fb7f6cb48709ef6b674d`

**Comment by dejury** [comment]
Any update(s) on this one?

**Comment by dejury** [comment]
Back again with an update on this issue. Found what the problem is, it is not related to packagist.

There is a versionnumber hardcoded in composer.json in the root of the project. This number is not updated in version 4.0.1 and 4.0.2.

I am not sure why this versionnumber is even there, I think it is better to remove this to prevent this issue in the future. Otherwise there should be a new release with the correct versionnumber inside the composer.json.

**Comment by rostockahoi** [comment]
Yes, the version number should be omitted in the composer file.

**Comment by fleaz** [comment]
Fixed in #411
