### ISSUE TITLE
Entry title not being used for SEO page title

### ISSUE THREAD

**Issue by andrewhawkes** [ethercreative/seo#479]
### Description

In the settings I have the default settings to use the entry title and site name:

<img width="704" alt="image" src="https://github.com/ethercreative/seo/assets/4975742/a716c22d-b29a-4d41-bd19-2bcc0e7eb653">

When creating a new entry, the title does not get used from the entry:

<img width="372" alt="image" src="https://github.com/ethercreative/seo/assets/4975742/911709d7-eb56-4a51-8f95-100bbc9f5326">

I noticed this started happening after upgrading from v5.0.0-rc1

### Steps to reproduce

1. Add a new entry which has the SEO field
2. The title of the entry is not used in the SEO title 

### Additional info

- Craft version:
- SEO version: v5.0.0-rc2
- PHP version: 8.2.15
- Database driver & version:	MySQL 8.0.33
- Other Plugins:

**Comment by scoch5** [comment]
Hi,
i have the same problem!

**Comment by pascalminator** [comment]
Can confirm I have the same exact problem on two different sites running Craft 5.

**Comment by jasonlav** [comment]
Changing it to `{{ title }}` to match `{{ siteName }}` does not appear to resolve the issue. Nor does `{{ entry.title }}`.

**Comment by jasonlav** [comment]
After further investigation, it appears there are multiple issues contributing to the problem.

1. The `_getVariables` method in `SeoData.php` only adds custom fields to the `$variables` array that compiles the title template. Adding the following snippet appends all native attributes of the entry to the `$variables` array.

```php
foreach ($this->_element->attributes() as $attribute) {
  $variables[$attribute] = $this->_element->{$attribute};
}
```

However, it probably isn't the best practice to do this since there could easily be naming conflicts. Rather, it would be better to add `element` as a new attribute of the `$variables` array. The title token would then be `{{ element.title }}`.

```php
if (!array_key_exists('element', $variables) && $this->_element)
  $variables['element'] = $this->_element;
```

2. The `_renderObjectTemplate` method in `SeoData.php` doesn't appear to be accepting the variables passed in. I ended up changing:
```php
$str = Craft::$app->view->renderObjectTemplate($template, $object);
```

To:
```php
$str = Craft::$app->view->renderObjectTemplate($template, [], $object);
```

In my testing these changes work. However, I'm not familiar enough with Craft's Element model and renderObjectTemplate to recommend this solution, otherwise I would submit a pull request. Perhaps the maintainer of the plugin can weigh in.

**Comment by pascalminator** [comment]
This problem is fixed now with v5.0.0-rc3. Thank you @Tam

**Comment by ryanfoote** [comment]
I think I have this same issue with v4.2.2 of the plugin. Has anyone else running the same version run into this error?

**Comment by andrewhawkes** [comment]
Not sure if this is part of the same issue - but if you have a title that contains a `|` or `-` only the text after those characters is used for the `{title}`

I.e. if the title of an entry is `ABC | 123` the meta title will be `123`
